# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SudokuMain.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(116, 90, 371, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_2.setFont(font)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.block5 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.block5.setFont(font)
        self.block5.setFrameShape(QtWidgets.QFrame.Box)
        self.block5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block5.setLineWidth(2)
        self.block5.setObjectName("block5")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.block5)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, 123, 123))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_7.setFont(font)
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.cell44 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell44.setFont(font)
        self.cell44.setFrameShape(QtWidgets.QFrame.Box)
        self.cell44.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell44.setText("")
        self.cell44.setAlignment(QtCore.Qt.AlignCenter)
        self.cell44.setObjectName("cell44")
        self.gridLayout_7.addWidget(self.cell44, 0, 0, 1, 1)
        self.cell64 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell64.setFont(font)
        self.cell64.setFrameShape(QtWidgets.QFrame.Box)
        self.cell64.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell64.setText("")
        self.cell64.setAlignment(QtCore.Qt.AlignCenter)
        self.cell64.setObjectName("cell64")
        self.gridLayout_7.addWidget(self.cell64, 0, 2, 1, 1)
        self.cell65 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell65.setFont(font)
        self.cell65.setFrameShape(QtWidgets.QFrame.Box)
        self.cell65.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell65.setText("")
        self.cell65.setAlignment(QtCore.Qt.AlignCenter)
        self.cell65.setObjectName("cell65")
        self.gridLayout_7.addWidget(self.cell65, 1, 2, 1, 1)
        self.cell54 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell54.setFont(font)
        self.cell54.setFrameShape(QtWidgets.QFrame.Box)
        self.cell54.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell54.setText("")
        self.cell54.setAlignment(QtCore.Qt.AlignCenter)
        self.cell54.setObjectName("cell54")
        self.gridLayout_7.addWidget(self.cell54, 0, 1, 1, 1)
        self.cell66 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell66.setFont(font)
        self.cell66.setFrameShape(QtWidgets.QFrame.Box)
        self.cell66.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell66.setText("")
        self.cell66.setAlignment(QtCore.Qt.AlignCenter)
        self.cell66.setObjectName("cell66")
        self.gridLayout_7.addWidget(self.cell66, 2, 2, 1, 1)
        self.cell56 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell56.setFont(font)
        self.cell56.setFrameShape(QtWidgets.QFrame.Box)
        self.cell56.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell56.setText("")
        self.cell56.setAlignment(QtCore.Qt.AlignCenter)
        self.cell56.setObjectName("cell56")
        self.gridLayout_7.addWidget(self.cell56, 2, 1, 1, 1)
        self.cell46 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell46.setFont(font)
        self.cell46.setFrameShape(QtWidgets.QFrame.Box)
        self.cell46.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell46.setText("")
        self.cell46.setAlignment(QtCore.Qt.AlignCenter)
        self.cell46.setObjectName("cell46")
        self.gridLayout_7.addWidget(self.cell46, 2, 0, 1, 1)
        self.cell45 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell45.setFont(font)
        self.cell45.setFrameShape(QtWidgets.QFrame.Box)
        self.cell45.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell45.setText("")
        self.cell45.setAlignment(QtCore.Qt.AlignCenter)
        self.cell45.setObjectName("cell45")
        self.gridLayout_7.addWidget(self.cell45, 1, 0, 1, 1)
        self.cell55 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell55.setFont(font)
        self.cell55.setFrameShape(QtWidgets.QFrame.Box)
        self.cell55.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell55.setText("")
        self.cell55.setAlignment(QtCore.Qt.AlignCenter)
        self.cell55.setObjectName("cell55")
        self.gridLayout_7.addWidget(self.cell55, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.block5, 1, 1, 1, 1)
        self.block7 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.block7.setFont(font)
        self.block7.setFrameShape(QtWidgets.QFrame.Box)
        self.block7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block7.setLineWidth(2)
        self.block7.setObjectName("block7")
        self.gridLayoutWidget_13 = QtWidgets.QWidget(self.block7)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(0, 0, 123, 123))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_13.setFont(font)
        self.gridLayoutWidget_13.setObjectName("gridLayoutWidget_13")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.cell17 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell17.setFont(font)
        self.cell17.setFrameShape(QtWidgets.QFrame.Box)
        self.cell17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell17.setText("")
        self.cell17.setAlignment(QtCore.Qt.AlignCenter)
        self.cell17.setObjectName("cell17")
        self.gridLayout_13.addWidget(self.cell17, 0, 0, 1, 1)
        self.cell37 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell37.setFont(font)
        self.cell37.setFrameShape(QtWidgets.QFrame.Box)
        self.cell37.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell37.setText("")
        self.cell37.setAlignment(QtCore.Qt.AlignCenter)
        self.cell37.setObjectName("cell37")
        self.gridLayout_13.addWidget(self.cell37, 0, 2, 1, 1)
        self.cell38 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell38.setFont(font)
        self.cell38.setFrameShape(QtWidgets.QFrame.Box)
        self.cell38.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell38.setText("")
        self.cell38.setAlignment(QtCore.Qt.AlignCenter)
        self.cell38.setObjectName("cell38")
        self.gridLayout_13.addWidget(self.cell38, 1, 2, 1, 1)
        self.cell27 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell27.setFont(font)
        self.cell27.setFrameShape(QtWidgets.QFrame.Box)
        self.cell27.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell27.setText("")
        self.cell27.setAlignment(QtCore.Qt.AlignCenter)
        self.cell27.setObjectName("cell27")
        self.gridLayout_13.addWidget(self.cell27, 0, 1, 1, 1)
        self.cell39 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell39.setFont(font)
        self.cell39.setFrameShape(QtWidgets.QFrame.Box)
        self.cell39.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell39.setText("")
        self.cell39.setAlignment(QtCore.Qt.AlignCenter)
        self.cell39.setObjectName("cell39")
        self.gridLayout_13.addWidget(self.cell39, 2, 2, 1, 1)
        self.cell29 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell29.setFont(font)
        self.cell29.setFrameShape(QtWidgets.QFrame.Box)
        self.cell29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell29.setText("")
        self.cell29.setAlignment(QtCore.Qt.AlignCenter)
        self.cell29.setObjectName("cell29")
        self.gridLayout_13.addWidget(self.cell29, 2, 1, 1, 1)
        self.cell19 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell19.setFont(font)
        self.cell19.setFrameShape(QtWidgets.QFrame.Box)
        self.cell19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell19.setText("")
        self.cell19.setAlignment(QtCore.Qt.AlignCenter)
        self.cell19.setObjectName("cell19")
        self.gridLayout_13.addWidget(self.cell19, 2, 0, 1, 1)
        self.cell18 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell18.setFont(font)
        self.cell18.setFrameShape(QtWidgets.QFrame.Box)
        self.cell18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell18.setText("")
        self.cell18.setAlignment(QtCore.Qt.AlignCenter)
        self.cell18.setObjectName("cell18")
        self.gridLayout_13.addWidget(self.cell18, 1, 0, 1, 1)
        self.cell28 = QtWidgets.QLabel(self.gridLayoutWidget_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell28.setFont(font)
        self.cell28.setFrameShape(QtWidgets.QFrame.Box)
        self.cell28.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell28.setText("")
        self.cell28.setAlignment(QtCore.Qt.AlignCenter)
        self.cell28.setObjectName("cell28")
        self.gridLayout_13.addWidget(self.cell28, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.block7, 2, 0, 1, 1)
        self.block3 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.block3.setFont(font)
        self.block3.setFrameShape(QtWidgets.QFrame.Box)
        self.block3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block3.setLineWidth(2)
        self.block3.setObjectName("block3")
        self.gridLayoutWidget_15 = QtWidgets.QWidget(self.block3)
        self.gridLayoutWidget_15.setGeometry(QtCore.QRect(0, 0, 123, 123))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_15.setFont(font)
        self.gridLayoutWidget_15.setObjectName("gridLayoutWidget_15")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridLayoutWidget_15)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.cell71 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell71.setFont(font)
        self.cell71.setFrameShape(QtWidgets.QFrame.Box)
        self.cell71.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell71.setText("")
        self.cell71.setAlignment(QtCore.Qt.AlignCenter)
        self.cell71.setObjectName("cell71")
        self.gridLayout_15.addWidget(self.cell71, 0, 0, 1, 1)
        self.cell91 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell91.setFont(font)
        self.cell91.setFrameShape(QtWidgets.QFrame.Box)
        self.cell91.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell91.setText("")
        self.cell91.setAlignment(QtCore.Qt.AlignCenter)
        self.cell91.setObjectName("cell91")
        self.gridLayout_15.addWidget(self.cell91, 0, 2, 1, 1)
        self.cell92 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell92.setFont(font)
        self.cell92.setFrameShape(QtWidgets.QFrame.Box)
        self.cell92.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell92.setText("")
        self.cell92.setAlignment(QtCore.Qt.AlignCenter)
        self.cell92.setObjectName("cell92")
        self.gridLayout_15.addWidget(self.cell92, 1, 2, 1, 1)
        self.cell93 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell93.setFont(font)
        self.cell93.setFrameShape(QtWidgets.QFrame.Box)
        self.cell93.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell93.setText("")
        self.cell93.setAlignment(QtCore.Qt.AlignCenter)
        self.cell93.setObjectName("cell93")
        self.gridLayout_15.addWidget(self.cell93, 2, 2, 1, 1)
        self.cell81 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell81.setFont(font)
        self.cell81.setFrameShape(QtWidgets.QFrame.Box)
        self.cell81.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell81.setText("")
        self.cell81.setAlignment(QtCore.Qt.AlignCenter)
        self.cell81.setObjectName("cell81")
        self.gridLayout_15.addWidget(self.cell81, 0, 1, 1, 1)
        self.cell83 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell83.setFont(font)
        self.cell83.setFrameShape(QtWidgets.QFrame.Box)
        self.cell83.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell83.setText("")
        self.cell83.setAlignment(QtCore.Qt.AlignCenter)
        self.cell83.setObjectName("cell83")
        self.gridLayout_15.addWidget(self.cell83, 2, 1, 1, 1)
        self.cell82 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell82.setFont(font)
        self.cell82.setFrameShape(QtWidgets.QFrame.Box)
        self.cell82.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell82.setText("")
        self.cell82.setAlignment(QtCore.Qt.AlignCenter)
        self.cell82.setObjectName("cell82")
        self.gridLayout_15.addWidget(self.cell82, 1, 1, 1, 1)
        self.cell73 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell73.setFont(font)
        self.cell73.setFrameShape(QtWidgets.QFrame.Box)
        self.cell73.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell73.setText("")
        self.cell73.setAlignment(QtCore.Qt.AlignCenter)
        self.cell73.setObjectName("cell73")
        self.gridLayout_15.addWidget(self.cell73, 2, 0, 1, 1)
        self.cell72 = QtWidgets.QLabel(self.gridLayoutWidget_15)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell72.setFont(font)
        self.cell72.setFrameShape(QtWidgets.QFrame.Box)
        self.cell72.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell72.setText("")
        self.cell72.setAlignment(QtCore.Qt.AlignCenter)
        self.cell72.setObjectName("cell72")
        self.gridLayout_15.addWidget(self.cell72, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.block3, 0, 2, 1, 1)
        self.block2 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.block2.setFont(font)
        self.block2.setFrameShape(QtWidgets.QFrame.Box)
        self.block2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block2.setLineWidth(2)
        self.block2.setObjectName("block2")
        self.gridLayoutWidget_17 = QtWidgets.QWidget(self.block2)
        self.gridLayoutWidget_17.setGeometry(QtCore.QRect(0, 0, 123, 123))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_17.setFont(font)
        self.gridLayoutWidget_17.setObjectName("gridLayoutWidget_17")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.gridLayoutWidget_17)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.cell41 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell41.setFont(font)
        self.cell41.setFrameShape(QtWidgets.QFrame.Box)
        self.cell41.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell41.setText("")
        self.cell41.setAlignment(QtCore.Qt.AlignCenter)
        self.cell41.setObjectName("cell41")
        self.gridLayout_17.addWidget(self.cell41, 0, 0, 1, 1)
        self.cell61 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell61.setFont(font)
        self.cell61.setFrameShape(QtWidgets.QFrame.Box)
        self.cell61.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell61.setText("")
        self.cell61.setAlignment(QtCore.Qt.AlignCenter)
        self.cell61.setObjectName("cell61")
        self.gridLayout_17.addWidget(self.cell61, 0, 2, 1, 1)
        self.cell62 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell62.setFont(font)
        self.cell62.setFrameShape(QtWidgets.QFrame.Box)
        self.cell62.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell62.setText("")
        self.cell62.setAlignment(QtCore.Qt.AlignCenter)
        self.cell62.setObjectName("cell62")
        self.gridLayout_17.addWidget(self.cell62, 1, 2, 1, 1)
        self.cell51 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell51.setFont(font)
        self.cell51.setFrameShape(QtWidgets.QFrame.Box)
        self.cell51.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell51.setText("")
        self.cell51.setAlignment(QtCore.Qt.AlignCenter)
        self.cell51.setObjectName("cell51")
        self.gridLayout_17.addWidget(self.cell51, 0, 1, 1, 1)
        self.cell63 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell63.setFont(font)
        self.cell63.setFrameShape(QtWidgets.QFrame.Box)
        self.cell63.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell63.setText("")
        self.cell63.setAlignment(QtCore.Qt.AlignCenter)
        self.cell63.setObjectName("cell63")
        self.gridLayout_17.addWidget(self.cell63, 2, 2, 1, 1)
        self.cell53 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell53.setFont(font)
        self.cell53.setFrameShape(QtWidgets.QFrame.Box)
        self.cell53.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell53.setText("")
        self.cell53.setAlignment(QtCore.Qt.AlignCenter)
        self.cell53.setObjectName("cell53")
        self.gridLayout_17.addWidget(self.cell53, 2, 1, 1, 1)
        self.cell43 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell43.setFont(font)
        self.cell43.setFrameShape(QtWidgets.QFrame.Box)
        self.cell43.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell43.setText("")
        self.cell43.setAlignment(QtCore.Qt.AlignCenter)
        self.cell43.setObjectName("cell43")
        self.gridLayout_17.addWidget(self.cell43, 2, 0, 1, 1)
        self.cell42 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell42.setFont(font)
        self.cell42.setFrameShape(QtWidgets.QFrame.Box)
        self.cell42.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell42.setText("")
        self.cell42.setAlignment(QtCore.Qt.AlignCenter)
        self.cell42.setObjectName("cell42")
        self.gridLayout_17.addWidget(self.cell42, 1, 0, 1, 1)
        self.cell52 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell52.setFont(font)
        self.cell52.setFrameShape(QtWidgets.QFrame.Box)
        self.cell52.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell52.setText("")
        self.cell52.setAlignment(QtCore.Qt.AlignCenter)
        self.cell52.setObjectName("cell52")
        self.gridLayout_17.addWidget(self.cell52, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.block2, 0, 1, 1, 1)
        self.block6 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.block6.setFont(font)
        self.block6.setFrameShape(QtWidgets.QFrame.Box)
        self.block6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block6.setLineWidth(2)
        self.block6.setObjectName("block6")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.block6)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(0, 0, 123, 123))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_8.setFont(font)
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.cell74 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell74.setFont(font)
        self.cell74.setFrameShape(QtWidgets.QFrame.Box)
        self.cell74.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell74.setText("")
        self.cell74.setAlignment(QtCore.Qt.AlignCenter)
        self.cell74.setObjectName("cell74")
        self.gridLayout_8.addWidget(self.cell74, 0, 0, 1, 1)
        self.cell94 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell94.setFont(font)
        self.cell94.setFrameShape(QtWidgets.QFrame.Box)
        self.cell94.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell94.setText("")
        self.cell94.setAlignment(QtCore.Qt.AlignCenter)
        self.cell94.setObjectName("cell94")
        self.gridLayout_8.addWidget(self.cell94, 0, 2, 1, 1)
        self.cell95 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell95.setFont(font)
        self.cell95.setFrameShape(QtWidgets.QFrame.Box)
        self.cell95.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell95.setText("")
        self.cell95.setAlignment(QtCore.Qt.AlignCenter)
        self.cell95.setObjectName("cell95")
        self.gridLayout_8.addWidget(self.cell95, 1, 2, 1, 1)
        self.cell84 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell84.setFont(font)
        self.cell84.setFrameShape(QtWidgets.QFrame.Box)
        self.cell84.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell84.setText("")
        self.cell84.setAlignment(QtCore.Qt.AlignCenter)
        self.cell84.setObjectName("cell84")
        self.gridLayout_8.addWidget(self.cell84, 0, 1, 1, 1)
        self.cell96 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell96.setFont(font)
        self.cell96.setFrameShape(QtWidgets.QFrame.Box)
        self.cell96.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell96.setText("")
        self.cell96.setAlignment(QtCore.Qt.AlignCenter)
        self.cell96.setObjectName("cell96")
        self.gridLayout_8.addWidget(self.cell96, 2, 2, 1, 1)
        self.cell86 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell86.setFont(font)
        self.cell86.setFrameShape(QtWidgets.QFrame.Box)
        self.cell86.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell86.setText("")
        self.cell86.setAlignment(QtCore.Qt.AlignCenter)
        self.cell86.setObjectName("cell86")
        self.gridLayout_8.addWidget(self.cell86, 2, 1, 1, 1)
        self.cell76 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell76.setFont(font)
        self.cell76.setFrameShape(QtWidgets.QFrame.Box)
        self.cell76.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell76.setText("")
        self.cell76.setAlignment(QtCore.Qt.AlignCenter)
        self.cell76.setObjectName("cell76")
        self.gridLayout_8.addWidget(self.cell76, 2, 0, 1, 1)
        self.cell75 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell75.setFont(font)
        self.cell75.setFrameShape(QtWidgets.QFrame.Box)
        self.cell75.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell75.setText("")
        self.cell75.setAlignment(QtCore.Qt.AlignCenter)
        self.cell75.setObjectName("cell75")
        self.gridLayout_8.addWidget(self.cell75, 1, 0, 1, 1)
        self.cell85 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell85.setFont(font)
        self.cell85.setFrameShape(QtWidgets.QFrame.Box)
        self.cell85.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell85.setText("")
        self.cell85.setAlignment(QtCore.Qt.AlignCenter)
        self.cell85.setObjectName("cell85")
        self.gridLayout_8.addWidget(self.cell85, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.block6, 1, 2, 1, 1)
        self.block9 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.block9.setFont(font)
        self.block9.setFrameShape(QtWidgets.QFrame.Box)
        self.block9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block9.setLineWidth(2)
        self.block9.setObjectName("block9")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.block9)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(0, 0, 123, 123))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_9.setFont(font)
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.cell77 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell77.setFont(font)
        self.cell77.setFrameShape(QtWidgets.QFrame.Box)
        self.cell77.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell77.setText("")
        self.cell77.setAlignment(QtCore.Qt.AlignCenter)
        self.cell77.setObjectName("cell77")
        self.gridLayout_9.addWidget(self.cell77, 0, 0, 1, 1)
        self.cell97 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell97.setFont(font)
        self.cell97.setFrameShape(QtWidgets.QFrame.Box)
        self.cell97.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell97.setText("")
        self.cell97.setAlignment(QtCore.Qt.AlignCenter)
        self.cell97.setObjectName("cell97")
        self.gridLayout_9.addWidget(self.cell97, 0, 2, 1, 1)
        self.cell98 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell98.setFont(font)
        self.cell98.setFrameShape(QtWidgets.QFrame.Box)
        self.cell98.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell98.setText("")
        self.cell98.setAlignment(QtCore.Qt.AlignCenter)
        self.cell98.setObjectName("cell98")
        self.gridLayout_9.addWidget(self.cell98, 1, 2, 1, 1)
        self.cell87 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell87.setFont(font)
        self.cell87.setFrameShape(QtWidgets.QFrame.Box)
        self.cell87.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell87.setText("")
        self.cell87.setAlignment(QtCore.Qt.AlignCenter)
        self.cell87.setObjectName("cell87")
        self.gridLayout_9.addWidget(self.cell87, 0, 1, 1, 1)
        self.cell99 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell99.setFont(font)
        self.cell99.setFrameShape(QtWidgets.QFrame.Box)
        self.cell99.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell99.setText("")
        self.cell99.setAlignment(QtCore.Qt.AlignCenter)
        self.cell99.setObjectName("cell99")
        self.gridLayout_9.addWidget(self.cell99, 2, 2, 1, 1)
        self.cell89 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell89.setFont(font)
        self.cell89.setFrameShape(QtWidgets.QFrame.Box)
        self.cell89.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell89.setText("")
        self.cell89.setAlignment(QtCore.Qt.AlignCenter)
        self.cell89.setObjectName("cell89")
        self.gridLayout_9.addWidget(self.cell89, 2, 1, 1, 1)
        self.cell79 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell79.setFont(font)
        self.cell79.setFrameShape(QtWidgets.QFrame.Box)
        self.cell79.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell79.setText("")
        self.cell79.setAlignment(QtCore.Qt.AlignCenter)
        self.cell79.setObjectName("cell79")
        self.gridLayout_9.addWidget(self.cell79, 2, 0, 1, 1)
        self.cell78 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell78.setFont(font)
        self.cell78.setFrameShape(QtWidgets.QFrame.Box)
        self.cell78.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell78.setText("")
        self.cell78.setAlignment(QtCore.Qt.AlignCenter)
        self.cell78.setObjectName("cell78")
        self.gridLayout_9.addWidget(self.cell78, 1, 0, 1, 1)
        self.cell88 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell88.setFont(font)
        self.cell88.setFrameShape(QtWidgets.QFrame.Box)
        self.cell88.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell88.setText("")
        self.cell88.setAlignment(QtCore.Qt.AlignCenter)
        self.cell88.setObjectName("cell88")
        self.gridLayout_9.addWidget(self.cell88, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.block9, 2, 2, 1, 1)
        self.block8 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.block8.setFont(font)
        self.block8.setFrameShape(QtWidgets.QFrame.Box)
        self.block8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block8.setLineWidth(2)
        self.block8.setObjectName("block8")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.block8)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(0, 0, 123, 123))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_10.setFont(font)
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.cell47 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell47.setFont(font)
        self.cell47.setFrameShape(QtWidgets.QFrame.Box)
        self.cell47.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell47.setText("")
        self.cell47.setAlignment(QtCore.Qt.AlignCenter)
        self.cell47.setObjectName("cell47")
        self.gridLayout_10.addWidget(self.cell47, 0, 0, 1, 1)
        self.cell67 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell67.setFont(font)
        self.cell67.setFrameShape(QtWidgets.QFrame.Box)
        self.cell67.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell67.setText("")
        self.cell67.setAlignment(QtCore.Qt.AlignCenter)
        self.cell67.setObjectName("cell67")
        self.gridLayout_10.addWidget(self.cell67, 0, 2, 1, 1)
        self.cell68 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell68.setFont(font)
        self.cell68.setFrameShape(QtWidgets.QFrame.Box)
        self.cell68.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell68.setText("")
        self.cell68.setAlignment(QtCore.Qt.AlignCenter)
        self.cell68.setObjectName("cell68")
        self.gridLayout_10.addWidget(self.cell68, 1, 2, 1, 1)
        self.cell57 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell57.setFont(font)
        self.cell57.setFrameShape(QtWidgets.QFrame.Box)
        self.cell57.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell57.setText("")
        self.cell57.setAlignment(QtCore.Qt.AlignCenter)
        self.cell57.setObjectName("cell57")
        self.gridLayout_10.addWidget(self.cell57, 0, 1, 1, 1)
        self.cell69 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell69.setFont(font)
        self.cell69.setFrameShape(QtWidgets.QFrame.Box)
        self.cell69.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell69.setText("")
        self.cell69.setAlignment(QtCore.Qt.AlignCenter)
        self.cell69.setObjectName("cell69")
        self.gridLayout_10.addWidget(self.cell69, 2, 2, 1, 1)
        self.cell59 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell59.setFont(font)
        self.cell59.setFrameShape(QtWidgets.QFrame.Box)
        self.cell59.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell59.setText("")
        self.cell59.setAlignment(QtCore.Qt.AlignCenter)
        self.cell59.setObjectName("cell59")
        self.gridLayout_10.addWidget(self.cell59, 2, 1, 1, 1)
        self.cell49 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell49.setFont(font)
        self.cell49.setFrameShape(QtWidgets.QFrame.Box)
        self.cell49.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell49.setText("")
        self.cell49.setAlignment(QtCore.Qt.AlignCenter)
        self.cell49.setObjectName("cell49")
        self.gridLayout_10.addWidget(self.cell49, 2, 0, 1, 1)
        self.cell48 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell48.setFont(font)
        self.cell48.setFrameShape(QtWidgets.QFrame.Box)
        self.cell48.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell48.setText("")
        self.cell48.setAlignment(QtCore.Qt.AlignCenter)
        self.cell48.setObjectName("cell48")
        self.gridLayout_10.addWidget(self.cell48, 1, 0, 1, 1)
        self.cell58 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell58.setFont(font)
        self.cell58.setFrameShape(QtWidgets.QFrame.Box)
        self.cell58.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell58.setText("")
        self.cell58.setAlignment(QtCore.Qt.AlignCenter)
        self.cell58.setObjectName("cell58")
        self.gridLayout_10.addWidget(self.cell58, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.block8, 2, 1, 1, 1)
        self.block4 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.block4.setFont(font)
        self.block4.setFrameShape(QtWidgets.QFrame.Box)
        self.block4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block4.setLineWidth(2)
        self.block4.setObjectName("block4")
        self.gridLayoutWidget_18 = QtWidgets.QWidget(self.block4)
        self.gridLayoutWidget_18.setGeometry(QtCore.QRect(0, 0, 123, 123))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_18.setFont(font)
        self.gridLayoutWidget_18.setObjectName("gridLayoutWidget_18")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.gridLayoutWidget_18)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.cell14 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell14.setFont(font)
        self.cell14.setFrameShape(QtWidgets.QFrame.Box)
        self.cell14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell14.setText("")
        self.cell14.setAlignment(QtCore.Qt.AlignCenter)
        self.cell14.setObjectName("cell14")
        self.gridLayout_18.addWidget(self.cell14, 0, 0, 1, 1)
        self.cell34 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell34.setFont(font)
        self.cell34.setFrameShape(QtWidgets.QFrame.Box)
        self.cell34.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell34.setText("")
        self.cell34.setAlignment(QtCore.Qt.AlignCenter)
        self.cell34.setObjectName("cell34")
        self.gridLayout_18.addWidget(self.cell34, 0, 2, 1, 1)
        self.cell35 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell35.setFont(font)
        self.cell35.setFrameShape(QtWidgets.QFrame.Box)
        self.cell35.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell35.setText("")
        self.cell35.setAlignment(QtCore.Qt.AlignCenter)
        self.cell35.setObjectName("cell35")
        self.gridLayout_18.addWidget(self.cell35, 1, 2, 1, 1)
        self.cell24 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell24.setFont(font)
        self.cell24.setFrameShape(QtWidgets.QFrame.Box)
        self.cell24.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell24.setText("")
        self.cell24.setAlignment(QtCore.Qt.AlignCenter)
        self.cell24.setObjectName("cell24")
        self.gridLayout_18.addWidget(self.cell24, 0, 1, 1, 1)
        self.cell36 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell36.setFont(font)
        self.cell36.setFrameShape(QtWidgets.QFrame.Box)
        self.cell36.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell36.setText("")
        self.cell36.setAlignment(QtCore.Qt.AlignCenter)
        self.cell36.setObjectName("cell36")
        self.gridLayout_18.addWidget(self.cell36, 2, 2, 1, 1)
        self.cell26 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell26.setFont(font)
        self.cell26.setFrameShape(QtWidgets.QFrame.Box)
        self.cell26.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell26.setText("")
        self.cell26.setAlignment(QtCore.Qt.AlignCenter)
        self.cell26.setObjectName("cell26")
        self.gridLayout_18.addWidget(self.cell26, 2, 1, 1, 1)
        self.cell16 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell16.setFont(font)
        self.cell16.setFrameShape(QtWidgets.QFrame.Box)
        self.cell16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell16.setText("")
        self.cell16.setAlignment(QtCore.Qt.AlignCenter)
        self.cell16.setObjectName("cell16")
        self.gridLayout_18.addWidget(self.cell16, 2, 0, 1, 1)
        self.cell15 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell15.setFont(font)
        self.cell15.setFrameShape(QtWidgets.QFrame.Box)
        self.cell15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell15.setText("")
        self.cell15.setAlignment(QtCore.Qt.AlignCenter)
        self.cell15.setObjectName("cell15")
        self.gridLayout_18.addWidget(self.cell15, 1, 0, 1, 1)
        self.cell25 = QtWidgets.QLabel(self.gridLayoutWidget_18)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell25.setFont(font)
        self.cell25.setFrameShape(QtWidgets.QFrame.Box)
        self.cell25.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell25.setText("")
        self.cell25.setAlignment(QtCore.Qt.AlignCenter)
        self.cell25.setObjectName("cell25")
        self.gridLayout_18.addWidget(self.cell25, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.block4, 1, 0, 1, 1)
        self.block1 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.block1.setFont(font)
        self.block1.setFrameShape(QtWidgets.QFrame.Box)
        self.block1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.block1.setLineWidth(2)
        self.block1.setObjectName("block1")
        self.gridLayoutWidget_19 = QtWidgets.QWidget(self.block1)
        self.gridLayoutWidget_19.setGeometry(QtCore.QRect(0, 0, 123, 123))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_19.setFont(font)
        self.gridLayoutWidget_19.setObjectName("gridLayoutWidget_19")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.gridLayoutWidget_19)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.cell11 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell11.setFont(font)
        self.cell11.setFrameShape(QtWidgets.QFrame.Box)
        self.cell11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell11.setText("")
        self.cell11.setAlignment(QtCore.Qt.AlignCenter)
        self.cell11.setObjectName("cell11")
        self.gridLayout_19.addWidget(self.cell11, 0, 0, 1, 1)
        self.cell31 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell31.setFont(font)
        self.cell31.setFrameShape(QtWidgets.QFrame.Box)
        self.cell31.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell31.setText("")
        self.cell31.setAlignment(QtCore.Qt.AlignCenter)
        self.cell31.setObjectName("cell31")
        self.gridLayout_19.addWidget(self.cell31, 0, 2, 1, 1)
        self.cell32 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell32.setFont(font)
        self.cell32.setFrameShape(QtWidgets.QFrame.Box)
        self.cell32.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell32.setText("")
        self.cell32.setAlignment(QtCore.Qt.AlignCenter)
        self.cell32.setObjectName("cell32")
        self.gridLayout_19.addWidget(self.cell32, 1, 2, 1, 1)
        self.cell21 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell21.setFont(font)
        self.cell21.setFrameShape(QtWidgets.QFrame.Box)
        self.cell21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell21.setText("")
        self.cell21.setAlignment(QtCore.Qt.AlignCenter)
        self.cell21.setObjectName("cell21")
        self.gridLayout_19.addWidget(self.cell21, 0, 1, 1, 1)
        self.cell33 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell33.setFont(font)
        self.cell33.setFrameShape(QtWidgets.QFrame.Box)
        self.cell33.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell33.setText("")
        self.cell33.setAlignment(QtCore.Qt.AlignCenter)
        self.cell33.setObjectName("cell33")
        self.gridLayout_19.addWidget(self.cell33, 2, 2, 1, 1)
        self.cell23 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell23.setFont(font)
        self.cell23.setFrameShape(QtWidgets.QFrame.Box)
        self.cell23.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell23.setText("")
        self.cell23.setAlignment(QtCore.Qt.AlignCenter)
        self.cell23.setObjectName("cell23")
        self.gridLayout_19.addWidget(self.cell23, 2, 1, 1, 1)
        self.cell13 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell13.setFont(font)
        self.cell13.setFrameShape(QtWidgets.QFrame.Box)
        self.cell13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell13.setText("")
        self.cell13.setAlignment(QtCore.Qt.AlignCenter)
        self.cell13.setObjectName("cell13")
        self.gridLayout_19.addWidget(self.cell13, 2, 0, 1, 1)
        self.cell12 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell12.setFont(font)
        self.cell12.setFrameShape(QtWidgets.QFrame.Box)
        self.cell12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell12.setText("")
        self.cell12.setAlignment(QtCore.Qt.AlignCenter)
        self.cell12.setObjectName("cell12")
        self.gridLayout_19.addWidget(self.cell12, 1, 0, 1, 1)
        self.cell22 = QtWidgets.QLabel(self.gridLayoutWidget_19)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cell22.setFont(font)
        self.cell22.setFrameShape(QtWidgets.QFrame.Box)
        self.cell22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cell22.setText("")
        self.cell22.setAlignment(QtCore.Qt.AlignCenter)
        self.cell22.setObjectName("cell22")
        self.gridLayout_19.addWidget(self.cell22, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.block1, 0, 0, 1, 1)
        self.TEST = QtWidgets.QLabel(self.centralwidget)
        self.TEST.setGeometry(QtCore.QRect(30, 490, 251, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TEST.sizePolicy().hasHeightForWidth())
        self.TEST.setSizePolicy(sizePolicy)
        self.TEST.setObjectName("TEST")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 430, 93, 28))
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 40, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TEST.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "Sudoku"))

